### ISSUE TITLE
Infinity calling onFetchData

### ISSUE THREAD

**Issue by atkawa7** [react-tools/react-table#445]
## What version of React-Table are you using?
react-table 6.5.3

## What bug are you experiencing, or what feature are you proposing?
I am using  react table manual version. Whenever `pages` is null react makes infinity calls to the server. This only happens when `NODE_ENV=production`. In `development` it works fine.

```javascript
<ReactTable manual columns={columns} data={this.state.results} onFetchData={this.handleChange.bind(this)} pages={this.state.pages} loading={this.state.loading} minRows={1} pageSizeOptions={[
              5,
              10,
              20,
              25,
              50,
              100,
              150,
              200,
              250,
              500
            ]}/>
          </div>
```

``` error
The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
```

**Comment by tannerlinsley** [comment]
Is this still happening for you?

**Comment by atkawa7** [comment]
@tannerlinsley  Yes it still happens. to stop it I had to change init state from `pages=null` to `pages=1`

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version.

**Comment by MikeZonnevijlle** [comment]
Hi, I'm still experiencing this issue. In my case page is NaN. I'm using 6.8.0
`<ReactTable
                                        columns={[
                                            {
                                                Header: 'Title',
                                                accessor: 'title'
                                            }, {
                                                Header: 'Last edited',
                                                accessor: 'lastEdited'
                                            }, {
                                                Header: 'Projects',
                                                accessor: 'projects',
                                                maxWidth: 150,
                                                sortable:false
                                            }, {
                                                Header: 'Options',
                                                accessor: 'projects',
                                                maxWidth: 150,
                                                width: 150,
                                                sortable:false,
                                                expander: true,
                                                Expander: ({ isExpanded, ...rest }) =>

                                                    <div>
                                                        <Link to="/dashboard" className="">
                                                            <i className="fa fa-share"></i>
                                                        </Link>
                                                        <Link to="/dashboard" className="">
                                                            <i className="fa fa-address-card"></i>
                                                        </Link>
                                                        {isExpanded
                                                            ? <i className="fa fa-minus"></i>
                                                            : <i className="fa fa-plus"></i>}
                                                    </div>,
                                            }
                                        ]}
                                        SubComponent={row => {
                                            return (
                                                <div style={{ padding: "20px" }}>
                                                    Sub component for {row.original.title}

                                                </div>
                                            );
                                        }}
                                        manual // Forces table not to paginate or sort automatically, so we can handle it server-side
                                        data={data}
                                        pages={pages} // Display the total number of pages
                                        loading={loading} // Display the loading overlay when we need it
                                        onFetchData={this.fetchSagaData.bind(this)} // Request new data when things change
                                        showPageSizeOptions={false}
                                        defaultPageSize={5}
                                        multiSort={false}
                                        className="-striped -highlight"
                                    />`

The first two calls out, page=NaN and then a third work correctly with page=0 on startup.
