### ISSUE TITLE
Table content not displayed

### ISSUE THREAD

**Issue by niteshjain132** [react-tools/react-table#529]
I'm using react: "^15.6.1" and react-table:"^6.5.3", tried to mock the below example, but the table data is not showing up i can only see the pagination boxes and nothing else, Please help
https://react-table.js.org/#/story/simple-table

Below is my code:

`import React, { Component } from "react";
import ReactTable from "react-table";
import "react-table/react-table.css";

export class ReactGridTable extends Component {
  render() {
    const data = [{ name: 'Tanner Linsley',  age: 26,   friend: {  name: 'Jason Maurer',  age: 23,  } },
                 { name: 'Tanner Linsley', age: 26, friend: { name: 'Jason Maurer', age: 23, }
  }];

  const columns = [{
    Header: 'Name',
    accessor: 'name' // String-based value accessors!
  }, {
    Header: 'Age',
    accessor: 'age',
    Cell: props => <span className='number'>{props.value}</span> // Custom cell components!
  }, {
    id: 'friendName', // Required because our accessor is not a string
    Header: 'Friend Name',
    accessor: d => d.friend.name // Custom value accessors!
  }, {
    Header: props => <span>Friend Age</span>, // Custom header components!
    accessor: 'friend.age'
  }];

    return (
      <div>  <ReactTable  data={data} columns={columns}/></div>
    );
  }
}`

**Comment by gary-menzel** [comment]
Can you put your version of the code into codesandbox ?

There are some lines in there that don't look like valid Javascript.

**Comment by kevinguard** [comment]
@niteshjain132 I'm having the exact issue. @gary-menzel BTW the code sandbox seems to be broken for me. I keep getting the following error:

![image](https://user-images.githubusercontent.com/20638978/31159879-1366e290-a881-11e7-916e-7a443275101e.png)

**Comment by gary-menzel** [comment]
You need to reset your codesandbox cache - it was happening to me as well (but it does work if you use incognito mode - that is how I worked out it was a cache issue).

I suspect codesandbox had some glitch that happened recently - no clear explanation but the cache clear fixed it for me.

**Comment by gary-menzel** [comment]
And I think I understand what you mean now. There is another "issue" that is still open where users are not seeing content in Chrome for some reason (I don't have that problem) and it may be related to a build environment issue (and not a react-table) issue.

**Comment by kevinguard** [comment]
Thanks @gary-menzel for the quick response. I suspect this is the reason. @niteshjain132 Can you post here a screenshot of the output (I want to see if you see the structure of the table but are missing only the content... to be 100% certain about the issue). Take a screenshot and copy the portion of the image you want and simply paste it in the editor. It will work correctly.

**Comment by niteshjain132** [comment]
Thanks @kevinguard and @gary-menzel  for the analysis, I will post the snapshot shortly..

**Comment by TWood67** [comment]
@gary-menzel I'm having this issue as well. Here is what my table looks like in chrome:
<img width="1289" alt="screen shot 2017-10-12 at 1 17 07 pm" src="https://user-images.githubusercontent.com/5759381/31517088-a9f17052-af4f-11e7-918d-b17e698cc8e6.png">

Here it is in firefox
<img width="1159" alt="screen shot 2017-10-12 at 1 17 42 pm" src="https://user-images.githubusercontent.com/5759381/31517108-bfcb23a0-af4f-11e7-8582-a4368026b176.png">

**Comment by gary-menzel** [comment]
For anyone still having this issue, please check the following FAQ and apply the recommended fix to your HTML doctype.....

https://github.com/react-tools/react-table/wiki/FAQ#my-reacttable-doesnt-seem-to-display-properly-on-browser-x---help

**Comment by TWood67** [comment]
Thanks for the fix, works great now!

**Comment by gary-menzel** [comment]
As this has been solved and answered in the FAQ and one other issue, I'll close it now.

**Comment by StevenZhangLC** [comment]
@TWood67 Hi I got exactly same problem with you, where did you add <!DOCTYPE html> ? I tried added it to index.html, but not working, still not showing data.

**Comment by gary-menzel** [comment]
@StevenZhangLC The proposed fixed was to solve the problem of the page navigation taking up all the space when using Chrome (yes, the recommendation is to add it at the top of your html page - before the `<html>` tag). The screenshot you have provided does not look like the same problem but rather looks like an issue with how you are rendering the columns. Are you able to demonstrate the issue with a small codesandbox sample and some dummy data?

**Comment by StevenZhangLC** [comment]
@gary-menzel Thanks a lot for the fast reply!

I am not sure how to embed a codesandbox here, so I just take a screen shot form codesandbox.
![screen shot 2017-10-17 at 1 59 54 pm](https://user-images.githubusercontent.com/32248179/31641791-82809fc8-b343-11e7-95ac-b4718251120d.png)

As you can see, the top two rows are so narrow, and when the mouse hover through it, it changed colour, like has data in it, but it is blank. 
And I added !DOCTYPE html to the top of html page. Same result.

Really appreciate for any help.

**Comment by gary-menzel** [comment]
Firstly, you can just copy link from the codesandbox and past it anywhere you like (others can edit it but not save it if they don't own the sandbox - they have to fork it).

Secondly, you should check back in the documentation and look at some of the examples. Your column definitions are incomplete.

`Header` is for the text you want displayed - not for the field you want to show.

You need to provide an `accessor` to tell react-table what you want to display in the column.

Given you are new to react-table you should probably consider joining the #react-table Slack channel (there is a badge at the top of the react-table documentation page). The github issues are mainly for feature requests and bug reporting (they are not really monitored for questions about usage).

**Comment by StevenZhangLC** [comment]
@gary-menzel Thank you so much Gary. It works now.
![screen shot 2017-10-17 at 2 47 28 pm](https://user-images.githubusercontent.com/32248179/31642923-31aa395e-b34a-11e7-9b61-081028a22cd2.png)

And thanks for your guide, now I get how to post codesandbox link here.

I do have Slack, and after your guide I joined the react-table channel, its real useful, thanks again.

After all, thanks for your patience. I learned a lot.

**Comment by Monesh1711** [comment]
@gary-menzel , i am facing a similar issue but in safari browser. When i load the table in chrome, it displays all the data perfectly but when i load it in safari browser the header takes up all the space. I have attached the snippets for both browser.

safari browser snippet -
![image](https://user-images.githubusercontent.com/53404428/80560737-c865c500-89ff-11ea-97d3-f95cd4b1698c.png)

chrome browser snippet - 
![image](https://user-images.githubusercontent.com/53404428/80560847-15e23200-8a00-11ea-929e-9a75a690dcdf.png)
