### ISSUE TITLE
Failed PropType errors on console?

### ISSUE THREAD

**Issue by tylerkeesling** [react-tools/react-table#583]
## What version of React-Table are you using?
6.7.1

## What bug are you experiencing, or what feature are you proposing?
My developer log in chrome is showing failed prop types for all the decorative component props.

<img width="752" alt="screen shot 2017-10-27 at 1 50 30 pm" src="https://user-images.githubusercontent.com/26422129/32122555-f438d0f4-bb1d-11e7-9935-faea3b88db5a.png">

Here is a snippet of my code: **the errors also show on the examples [here](https://react-table.js.org/#/story/simple-table)
`  render() {

    const columns = [
      {
        Header: 'id',
        accessor: 'id'
      }, {
        Header: 'Name',
        accessor: 'name'
      }
    ]

    return (
      <div className='content'>
        <NavBar />
        {
          this.state.showModal ? <PlayerModal /> : null
        }
        <ReactTable
          data={this.props.teamStats}
          columns={columns}
        />
      </div>
    )
  }
}`

**Comment by wootencl** [comment]
+1 I imagine this is related to the changes that were put out with 6.7.1 which was just released less than thirty minutes ago

/cc @tannerlinsley

**Comment by tannerlinsley** [comment]
Hang tight

**Comment by tannerlinsley** [comment]
Should be fixed in latest version. Confirm?

**Comment by wootencl** [comment]
Still getting one it looks like:

<img width="719" alt="screen shot 2017-10-27 at 4 42 37 pm" src="https://user-images.githubusercontent.com/8561687/32124475-855ba304-bb2d-11e7-9fe4-c449e3285e53.png">

**Comment by tannerlinsley** [comment]
Patched. Try again.

**Comment by tannerlinsley** [comment]
BTW, sorry about this one guys. Somehow this PR slipped past me on testing.

**Comment by wootencl** [comment]
No worries. Happens to the best of us.

 That last patch seemed to do the trick though. No more warnings 🎉

**Comment by gary-menzel** [comment]
V 6.7.4 seems to resolve the last of the propTypes issues.
