### ISSUE TITLE
footerClassName is not honored

### ISSUE THREAD

**Issue by hansena** [react-tools/react-table#598]
## What version of React-Table are you using?
**6.7.4**

## What bug are you experiencing, or what feature are you proposing?
**footerClassName is not being honored**

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
**[https://codesandbox.io/s/r1xnrox1o](https://codesandbox.io/s/r1xnrox1o)**

## What are the steps to reproduce the issue?
1. create a table with a footer
2. apply a class using footerClassName
3. footer renders without class

**Comment by hansena** [comment]
fixed in #619

**Comment by gutenye** [comment]
@gary-menzel @hansena still not work with latest version v6.7.6
Tested in https://codesandbox.io/s/9z8469xlpw

**Comment by gary-menzel** [comment]
Yes - but it looks like the fix provided by @hansena was not properly merged into the file.

But there are workarounds....

You'll have to use ` getTfootTdProps` override on the table (and return a `className` in the object) until it can be looked at again.

You can also override `getFooterProps` on the column and do the same thing.

There are no automated tests and there are probably too many places where the same thing can be done.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!

**Comment by CaitlinWeb** [comment]
I encountered this issue with version 6.8.5. Can this be reopened?

**Comment by pouretrebelle** [comment]
+1
Still having this issue on 6.8.6

**Comment by thedustyrover** [comment]
this is still occuring on 6.9.2. Here is a sandbox example, the last name footer is set to text-right which is not set:

https://codesandbox.io/s/y51w2k17x

**Comment by JamesFysh-alliance** [comment]
Still an issue in 6.10.0.

Seems like a trivial fix;

```
    const makeHeader = (column, i) => {
    ...
      const classes = [
        ```column.headerClassName,```
        theadThProps.className, 
        columnHeaderProps.className
]
```
```
    const makeColumnFooter = (column, i) => {

      const classes = [
        column.footerClassName,
        tFootTdProps.className,
        column.className,
        columnProps.className,
        columnFooterProps.className,
      ]
```

**Comment by pixelwhip** [comment]
This still appears to be an issue in 6.10.3.  @gary-menzel's workaround worked for me. 

Instead off defining 
```
footerClassName: 'custom-class'
```
try:
```
getFooterProps: () => ({
  className: 'custom-class'
}),
```
