### ISSUE TITLE
content mismatch with server-side rendering

### ISSUE THREAD

**Issue by Tomekmularczyk** [react-tools/react-table#989]
## What version of React-Table are you using?

    "react-table": "^6.8.6",

## What bug are you experiencing, or what feature are you proposing?

> Warning: Text content did not match. Server: "5 rows" Client: "5"

## What are the steps to reproduce the issue?

I'm using NextJS which does server-side-rendering of the HTML markup and there's some mismatch between what's rendered on a server and what on the client.

**Comment by tannerlinsley** [comment]
This has been fixed in a recent PR, but has not yet been released. Stay tuned for the next release.

**Comment by vjpr** [comment]
@tannerlinsley Is this released yet?

I am still seeing it in v6.8.6.
